# Generated by Django 5.0.6 on 2024-07-31 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='latiude',
            new_name='latitude',
        ),
    ]
